apiVersion: v1
kind: Service
metadata:
  name: nginx-loadbalancer-service
spec:
  type: LoadBalancer # ClusterIp, # NodePort
  selector:
    app: rollingupdate-strategy
  ports:
    - name: http
      port: 80 # Service Port
      targetPort: 80 # Container Port
